site:
  url: 'http://localhost/addon-template/demo/'

templates:
  site:
    name: Demo Leafcutter site

cache:
  driver: ephemeral
  directory: '${base_dir}/cache/'

assets:
  output:
    directory: '${base_dir}/assets/'
    url: '@/assets/'
